[[defaults]]
=== Changing Defaults

You can override the configuration defaults very easily.

Let's suppose you do not want any message conversion on listeners. If a listener container has no `messageConverter` listeners will receive raw messages. So we want to override the standard listener container definition to set the `messageConverter` property to `null`.

In your application's `application.groovy`

[source,groovy]
----
grails.plugin.jms {
    containers {
        standard {
            messageConverter = null
        }
    }
}
----

This definition will get merged against the plugin provided defaults to produce a standard listener container definition with `messageConverter` set to `null`.

==== Disabling the default dependency on the Persistence Interceptor.

If you are not using any *GORM* implementation such as *Grials' Hibernate Plugin*
(i.e. you uninstalled the *hibernate* plugin) or the *GORM* implementation you are using doesn't provide a
**Persistence Interceptor Bean**, you will have to disable the _default_
dependency to the **Persistence Interceptor Bean**. You can do this by setting
in the `application.groovy` the `grails.plugin.jms.adapters.standard.persistenceInterceptorBean` to `null` .

[source,groovy]
----
grails.plugin.jms {
    adapters {
        standard {
            persistenceInterceptorBean = null
        }
    }
}
----
