This plugin is built on top of http://static.springsource.org/spring/docs/3.0.x/reference/html/jms.html.[Spring's JMS support]
There are some core Spring JMS concepts that you should at least be aware of.


== JmsTemplate

Spring provides http://static.springsource.org/spring/docs/3.0.x/javadoc-api/org/springframework/jms/core/JmsTemplate.html[JmsTemplate] which is what this plugin uses to send messages.

== MessageConverter

The http://static.springsource.org/spring/docs/3.0.x/javadoc-api/org/springframework/jms/support/converter/MessageConverter.html[MessageConverter] abstraction conveniently allows pluggable message conversion.
By default, this plugin uses Spring's http://static.springsource.org/spring/docs/3.0.x/javadoc-api/org/springframework/jms/support/converter/SimpleMessageConverter.html[SimpleMessageConverter] which handles 'standard' message payloads and JMS Message types.

== MessageListenerContainer

A listener container polls a JMS destination for messages.
Each listener (i.e. each service method that receives JMS messages) has it's own listener container.

This plugin uses the http://static.springsource.org/spring/docs/3.0.x/javadoc-api/org/springframework/jms/listener/DefaultMessageListenerContainer.html[DefaultMessageListenerContainer] implementation.

== MessageListenerAdapter

A listener adapter connects a listener container to the actual destination of the message.
It handles message conversion amongst other things.

By default, this plugin uses a http://static.springsource.org/spring/docs/3.0.x/javadoc-api/org/springframework/jms/listener/adapter/MessageListenerAdapter.html[MessageListenerAdapter] subclass that is Grails aware and sets up the necessary Grails environment for listener methods (e.g. Hibernate session).
