There are some noteworthy things about this config syntax.


=== Bean names

The beans created automatically get suffixes applied to them.
Template bean names get suffixed with 'JmsTemplate', container beans get suffixed with 'JmsListenerContainer' and adapter beans get suffixed with 'JmsListenerAdapter'.

=== Setting Beans

To set a property to another Spring bean, simply append `Bean` to the property name and set the property to the name of the bean.

Here is how the standard template is defined to use the bean named `jmsConnectionFactory` as it's connection factory...

[source,groovy]
----
templates {
    standard {
        connectionFactoryBean = "jmsConnectionFactory"
    }
}
----

=== Setting Class

To set the class of a bean, you must use the following syntax

[source,groovy]
----
templates {
    standard {
        meta {
            clazz = my.org.CustomJmsTemplate
        }
    }
}
----

=== Extending Definitions

Bean definition can inherit from parents and selectively override settings.

[source,groovy]
----
templates {
    other {
        meta {
            parentBean = 'standardJmsTemplate'
        }
        connectionFactoryBean = "someOtherJmsConnectionFactory"
    }
}
----

This creates an "other" template, that inherits all of the standard settings but uses a custom connectionFactory.
