[[springJms]]
=== Spring JMS

This plugin is built on top of {spring_jms}[Spring's JMS support].

There are some core Spring JMS concepts that you should at least be aware of.

==== JmsTemplate

Spring provides {jms_template}[JmsTemplate]: which is what this plugin uses to send messages.

==== MessageConverter

The {message_converter}[MessageConverter] abstraction conveniently allows pluggable message conversion. By default, this plugin uses Spring's {simple_msg_converter}[SimpleMessageConverter] which handles 'standard' message payloads and JMS Message types.

==== MessageListenerContainer

A listener container polls a JMS destination for messages. Each listener (i.e. each service method that receives JMS messages) has it's own listener container.

This plugin uses the {default_message_listener}[DefaultMessageListenerContainer]: implementation.

==== MessageListenerAdapter

A listener adapter connects a listener container to the actual destination of the message. It handles message conversion amongst other things.

By default, this plugin uses a {msg_listener_adapter}[MessageListenerAdapter] subclass that is Grails aware and sets up the necessary Grails environment for listener methods (e.g. Hibernate session).