name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '00 06 * * 1'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue looks like it is stale and therefor it is in risk of being closed with no further action.'
        stale-pr-message: 'This pull request looks like it is stale and therefor it is in risk of being closed with no further action.'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
        days-before-stale: 180
